apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook
  namespace: validation
webhooks:
  - name: warden.validation.svc
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions: ["v1","v1beta1"]
    rules:
      - apiGroups: ["apps", ""]
        resources:
          - "deployments"
          - "pods"
        apiVersions:
          - "*"
        operations:
          - CREATE
    clientConfig:
      service:
        name: warden
        namespace: validation
        path: /validate/
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURLVENDQWhHZ0F3SUJBZ0lVSTJ0dEUwRFBrbXdHazRoYUFFajRCMU13dXBZd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0pERWlNQ0FHQTFVRUF3d1pWMkZ5WkdWdUlFTnZiblJ5YjJ4c1pYSWdWMlZpYUc5dmF6QWVGdzB5TkRBMQpNVEV4TXpBek16aGFGdzB5TlRBMU1URXhNekF6TXpoYU1DUXhJakFnQmdOVkJBTU1HVmRoY21SbGJpQkRiMjUwCmNtOXNiR1Z5SUZkbFltaHZiMnN3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQzMKSDhaK3VHQjZIcWgwOEVIZUFQZUdlQnZVd3ZqTVB5ZXR6K2NKRDhIc3QxQUcrdUx0RHlEZ1V1eEo2ZHJtY2NRZgprQjNKcVQ3NzBMNVNsWTgxSFprcEdmTXBsU2E5U29TTHYxcFdjZFVqOEMrd0hJVVJrVXVJMHBWYVd0bXRVRU1yClJGL0FzS25YeUYyY09URzVzZ2lHTmtUdlpWYmZpM1RQclo4cE9LNHFUOW9Da2tlNlRTRndjdm5IakZOTmg3dVMKTEd0U2NYRHNrMFNJOFFNWW9pYkxoNEFYNEJMbEpjTjlPc0YrdHJvbEMyeUNRZkNVZlh6MU9JUXFLb2FZeDYxUwpldGNMQlFiNC9DSzBvOGs0cS9OZ2tDYjREYm81TW0yQXN1Wmk2RHhIOEZzdWcxZ0VTNzNuSVJSbDMySHJNbURFClF3UlZiVjl2dk5Sbk1ZV0tDbXh6QWdNQkFBR2pVekJSTUIwR0ExVWREZ1FXQkJRSld3NTJLYlNtZEY1cW5OcDUKVWROWW1tNTVPREFmQmdOVkhTTUVHREFXZ0JRSld3NTJLYlNtZEY1cW5OcDVVZE5ZbW01NU9EQVBCZ05WSFJNQgpBZjhFQlRBREFRSC9NQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUJjNnVCV1VPYWhVZ0VFeU5FUWplNnlGNUx1CnoweUp4amxBQ3F2ZWtrcHVnZEJiMFU4NXV2NkZ2VVdQTjFsQmlxYVdpSWlWd0NRUDBPdm1tOUZWa29wQ0VhZEwKalNaOGxWRFI3VlVQRlZDUUhqMGZVYUVidFhJSUg0VllFVGVHRHVtclozWnVibXhHZXRjbkFoTmlFTk94QlEzZgo1aERxZU8xeHRBbU1WV0EvQlhnZm0vS3NhOVJNQXNIOEx2TFRVUFVXNkE1YjMrQVVxRkhrZlJqWDJadHBGU2EwCmVjcXE3cjJIZ2grcUNYZzBjMExJWHI4ZDJlUytkRGtwRHNicXkvYWpJc0x4cUszVFkrTWdlQm53Tmd0QWZ3dFkKN1ppM3NXUDNSSlN3Rkloc1M0aU5JZ1JLbm4xM0RFd2pFbXF2cjVXMGRkY3lnQ3BTNm5RRG95U3dtdUF2Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K

